### ISSUE TITLE
status incorrectly reports patched package as out-of-date

### ISSUE THREAD

**Issue by kaey** [kardianos/govendor#102]
govendor version ab600ff

Sometimes I have to patch vendored libraries, but cannot get it upstream.

This is how govendor status works:
```
$ govendor fetch github.com/jaytaylor/html2text
$ govendor status
$ patch vendor/github.com/jaytaylor/html2text/html2text.go patches/html2text_table.patch
patching file vendor/github.com/jaytaylor/html2text/html2text.go
$ govendor status
The following packages are out-of-date:
        github.com/jaytaylor/html2text
```

It should say something about checksum mismatch, not out-of-date.

**Comment by kardianos** [comment]
This is by design. I will start a FAQ document that lists out other options.

The recommended thing to do in this case is to:
`govendor fetch github.com/jaytaylor/html2text::github.com/kaey/html2text`
(assumes you have pushed your changes to your own fork). This set the origin to the kaey repo but copies them into jaytaylor.

Writing down a revision that doesn't exist anywhere or checking in changes to vendor that can't be traced back to a source is not recommended. You can do it, but it will boldly state that it is out of date. This is similar to using `govendor add -uncommitted <modified-package>`. Great for trying out changes without committing them, but `govendor status` is designed to highlight these changes to the user.

**Comment by kardianos** [comment]
I'm going to close for now. Feel free to re-open if you feel this is in error.

**Comment by kaey** [comment]
The problem is (as I understand it) this command intented for those who don't commit vendor folder to their repo.
For those who do, out-of-date message doesn't make any sense.
Maybe change it to "out of date or modified locally" and describe in docs both usecases?

Sorry I didn't answer earlier.

**Comment by kardianos** [comment]
SGTM
