### ISSUE TITLE
Add tags to revision

### ISSUE THREAD

**Issue by gaillard** [kardianos/govendor#144]
The tool is fantastic and I hope it becomes the defacto vendoring tool since it's nice and focused and getting more and more robust! But I still have to ask for a tiny feature :) to put any tag information for a commit in the vendor.json. it would be very nice to be able to see we are using v2 along with the commit hash. Thanks for the tool!

**Comment by gaillard** [comment]
Could be good to put the tool name in the vendor.json too

**Comment by kardianos** [comment]
@gaillard 
RE tag: Right now the tag name will be added in the version field if you specify it with "package/...@tag". But it won't be added automatically. This is by design. Would this meet your needs?

RE tool name: It was there in there before, but there were several devs who requested it be removed who made valid points, namely preventing unneeded changes if multiple tools were used on the same repo.

**Comment by gaillard** [comment]
It would yes, thanks. The tool name as an option or the first tool to put it there or instead labeled last tool name all sound like options?

**Comment by kardianos** [comment]
@gaillard I think I'm going to hold off for now on putting the tool name in there.
