### ISSUE TITLE
Only list duplicate GOPATH packages with -v on.

### ISSUE THREAD

**Issue by jefferai** [kardianos/govendor#157]
I'm hitting some strange behavior and @sean- suggested putting in the status of things in a bug report.

I added a new dependency (`github.com/hashicorp/scada-client/scada`) in my code and was trying to have `govendor` tell me which packages are missing.

The package to pay attention to is `go-multierror`, which already exists in `vendor/` and at the same revision.
```
$ govendor list +missing

$ govendor list +outside
 e  github.com/armon/go-metrics                
 e  github.com/hashicorp/errwrap               
 e  github.com/hashicorp/go-msgpack/codec      
 e  github.com/hashicorp/go-multierror         
 e  github.com/hashicorp/net-rpc-msgpackrpc    
 e  github.com/hashicorp/scada-client          
 e  github.com/hashicorp/scada-client/scada    
 e  github.com/hashicorp/yamux                 

$ find vendor -type d | grep multierror
vendor/github.com/hashicorp/go-multierror

$ govendor add github.com/hashicorp/go-multierror
Error: Package "github.com/hashicorp/vault/vendor/github.com/hashicorp/go-multierror" already in vendor.

$ govendor status

$ govendor list +out,^vend
 e  github.com/armon/go-metrics                
 e  github.com/hashicorp/errwrap               
 e  github.com/hashicorp/go-msgpack/codec      
 e  github.com/hashicorp/go-multierror         
 e  github.com/hashicorp/net-rpc-msgpackrpc    
 e  github.com/hashicorp/scada-client          
 e  github.com/hashicorp/scada-client/scada    
 e  github.com/hashicorp/yamux
```
So basically, I have no idea what `govendor` is doing here. `+missing` reports nothing even though there's a new dependency in my code. I don't understand what it's trying to tell me about `go-multierror` since as far as I can tell that last command should be filtering out anything that's vendored alredy. I should also mention that several of the other items listed in external are also already vendored (such as `errwrap`).

It's entirely possible that the behavior with `go-multierror` is exactly what is expected, except then how do I differentiate between packages that are already vendored, and those that are not, especially when `+missing` shows me nothing and the new dependency that isn't vendored simply shows up as external:
```
 e  github.com/hashicorp/scada-client/scada    
    └──  l  github.com/hashicorp/vault/command/server
```

**Comment by kardianos** [comment]
I'm guessing the reason `go-multierror` is showing up as "external" is that there is another package you are referencing in GOPATH (external) that is using `go-multierror`. The important thing to keep in mind is that go compiles things per package, and govendor reflects that. So if a GOPATH package that you use references `go-multierror` and a local package references `go-multierror`, you are referencing two different distinct packages, each called `go-multierror`.

At least, that what it sounds like to me. If you'd like, show the output of either `govendor list -v +out` or `govendor list -v`. That can usually tell conclusively what is happening.

**Comment by evanphx** [comment]
@jefferai `+missing` only reports packages that are neither in `vendor/` nor `$GOPATH`, in other words, missing from this machine.

**Comment by jefferai** [comment]
@kardianos The new package only exists in GOPATH and isn't yet vendored, so in turn it's referencing a package which is both vendored and in GOPATH, and so on. I understand that they are technically different packages, and maybe I had some unreasonable expectations for what govendor would analyze/tell me, but I still cannot figure out how to get govendor to tell me, at a single level, which packages are missing from vendor/. I basically want the opposite of +unused. So if I add A as a dependency in my code, which references B, C, D, and E, all of which exist both in GOPATH and vendor/, how do I get govendor to just say A?

**Comment by kardianos** [comment]
I understand.

The problem with just saying "A", is that isn't a complete picture of what is going on. Actually, govendor used to have this behavior but I considered it a bug. For convenience govendor list only shows the "import path", not the disk path from GOPATH/src root. And the "import path" can be both referenced from vendor folder and GOPATH.

`govendor +out` will give you `+missing +external`. 

Can you take a step back and give the motivation for wanting it to just say "A" (from example above)? So far what I see is a design issue, so I'd like to understand the motivation.

**Comment by jefferai** [comment]
Hi @kardianos ,

Basically, what I wanted to figure out was what packages had been added to the project that had not already been a part of the project. I realize that I could use `govendor` to simply add `external` (or `outside`) packages and then use `git status` to take a look, but I figured that `govendor` would be able to do this for me without requiring an external tool. (Also, attempting to add a package that already exists in `vendor/` results in an error, so I don't know whether or not that holds true if some packages in a list already exist or whether it simply adds what doesn't exist yet.)

I understand what you're saying above about you considering the old behavior a bug -- but it's actually the behavior that I want/was expecting. The fact that a package in GOPATH is a different package (in terms of the Go compiler) to one in `vendor` is only interesting to me in the sense that if I am referencing an external package, I need to fix my vendored deps so that I am *not* be referencing such a package.

So in other words, I was looking for a way to understand _which items I need to vendor_. In this sense, it's unintuitive to be showing the full set of deps in GOPATH when 9/10 of them are already in `vendor/` -- as soon as I put the 10th in `vendor/`, those cease to be relevant...and in fact, in some sense they're already irrelevant because whatever version of those packages live in `vendor/` are going to be the versions that my new dep will be using as soon as I add it to `vendor/`.

One thing that might have been useful would have been to show a different status letter for items in GOPATH (but not vendor) that are referenced directly from my project vs ones that are shown because they are referenced from that first set.

Alternately, changing the meaning of `missing` might be useful; to me it's generally not useful to know which packages are not found in either `vendor/` or GOPATH, because either way we can assume build will fail -- I'm going to know about this right away.

I can imagine other potential ways to tackle this. What are your thoughts so far?

**Comment by kardianos** [comment]
I'm sympathetic to this request.

Right now I want `govendor list` to show by default the status of packages, as they would be compiled. This default output is really useful when people get odd compiler messages. My answer is always, "run govendor list -v", then they say, "oohh, that package is in two different places, used here as X and here as Y".

However, rather than add a new status or change the default behavior, what if I added a flag to `list` that removed the package from the list if the canonical name was already in the vendor folder?

I'm not sure what it would be called... `-reduce` or ... I'll need to think about it. Thoughts?

**Comment by sean-** [comment]
@Kardianos You bring up an interesting point, is govendor intended primarily for consumers and users of a project, or developers releasing software? I actually really liked the old behavior of missing and am +1 for restoring its old behavior because it fit the option's semantics (I actually didn't realize the behavior had changed until walking through this problem with @jefferai).

From a release engineering perspective, if you're looking for suggestions, how about +dist? That option will tell you whatever you need regarding making a release to distribute a piece of software. In this case it would let you know what was referenced in the project but external to vendor/. ?

**Comment by jefferai** [comment]
I actually like @sean- 's suggestion of `+dist`. One common problem we have is that someone will add a dep, not realize it, and commit, breaking tests and others' compilations. In other words, the code cannot be distributed. We could encourage a workflow of blindly adding a `govendor add` and/or `govendor update` but I think that will end up causing problems too with the current status primitives since we may end up adding/updating more than we intended.

A flag to make it clear what needs to be added for the code to be distributable makes intuitive sense to me. This would work similarly to what you suggested as a `reduce` flag but could be a target for adding/updating.

I also suggest that the help description for `missing` be updated. When it says `referenced packages but not found`, it immediately follows to wonder "not found _where_?" And you may, like me, come up with the wrong conclusion that it means _not found in the vendor folder_. Perhaps `referenced packages not found in vendor folder or GOPATH`?

**Comment by kardianos** [comment]
@jefferai @sean- 
I'm actually confused now. I'm open to doing a quick google hangout if you'd like...

So govendor is mainly targeted at developers who add and remove deps from a project. Other then maybe `govendor sync`, other devs or users shouldn't be using govendor.

If a package is listed as external, then **that package will be compiled from GOPATH, not govendor, even if that package is alreaady in the vendor folder**. I want to make that very clear. It doesn't matter if it is already in the vendor folder. You are referencing at least another package rooted in GOPATH/src that is referencing that package you thought you were building from the vendor folder. But actually you are building from GOPATH/src.

As an experiment, create a new GOPATH folder, set the GOPATH env, clone your project into the correct folder, then try to build it, try to run govendor.

I could be misunderstanding what you are saying here?
---

Lastly, most of the functionality is housed in the context and run packages in govendor. I'm open to other interface ideas and trying them out; the tool is nicely modular that makes that relatively easy to do. Again, I may be missing the point of what you are saying and I'm open to a quick conf call/hangout to clarify. (email me directly if you want to do that, I'm free today, most of tomorrow).

**Comment by jefferai** [comment]
> So govendor is mainly targeted at developers who add and remove deps from a project. Other then maybe govendor sync, other devs or users shouldn't be using govendor.

Sure -- but this is, in my case, three people. We don't have some central person who is responsible for adding or removing deps. When one of the team members adds a dep, they are the one that then needs to update the vendoring.

> If a package is listed as external, then that package will be compiled from GOPATH, not govendor, even if that package is alreaady in the vendor folder.

I may be wrong, but I believe this is only partly true. If a package is listed as external but is *also* vendored, then I believe packages that are not vendored will use the package from the GOPATH, but packages that are vendored will use the vendored copy. Is that correct? Or are you saying that if you reference a package X from multiple places (both in vendored deps and unvendored deps) that *all* packages referencing X will use the external copy?

The answer to that question is interesting but kind of academic, because either way, what I want is to fix that situation. If I have A, B, C, D, and E listed as external, but A, B, C, and D are also vendored and only being brought in from the GOPATH because of E, I want to know that E is the reason that this is happening, both so that I can confirm that the set of packages that I need to vendor is what I expect, and so that I can `govendor add E`.

That was the point behind Sean's suggestion of `+dist` -- having it tell you the set of packages that need to be added to vendoring in order for the sources to be properly distributable. In my example above, that's not A, B, C, or D, but only E.

We can hang out if you'd like -- what's your time zone? Sean is up in the air right now, but there's no real rush.

**Comment by kardianos** [comment]
> Sure -- but this is, in my case, three people. We don't have some central person who is responsible for adding or removing deps. When one of the team members adds a dep, they are the one that then needs to update the vendoring.

Sounds good. No issue here.

> I may be wrong, but I believe this is only partly true. If a package is listed as external but is also vendored, then I believe packages that are not vendored will use the package from the GOPATH, but packages that are vendored will use the vendored copy. Is that correct?

Assuming only direct dependencies, yes. So you might compile two different packages with the same import path.

If you run `govendor add +external`, it won't re-add a package it already has in vendor, but it will add the other packages that are not present. But I do get that what you want to see .

 * Packages you want to add (not yet vendored)
 * vs Packages as a compiler would see it (current).

The first may help people who have a partially vendored state, or want to script with other tools, or don't want to add packages with "+external". The second helps devs understand why their app isn't compiling (I already *have* package X, why is it complaining?). Option: switch to the second only when the "verbose" flag is used. Otherwise remove status entries for already vendored packages.

I'm in Pacific (PDX) timezone.

**Comment by kaedys** [comment]
Aside from everything else, I'd like to throw in a suggestion for a new flag (or modify an existing flag and add another to retain current behavior), that shows me only _highest-level unvendored_ dependencies.  This would accomplish the just-show-A behavior that @jefferai was looking for, and would clean up the list view for many use cases.

Basically, the idea would be that a package would only be reported if it was both absent from the vendor folder and either directly referenced by the project, or referenced by a chain of already vendored dependencies.  If a missing package is solely referenced by other unvendored dependencies, it would not be shown.  If we have the following:

A
B
C - Imports A
D - Imports B
E - Imports D
F
G
H - Imports F and G
**Project** - Imports C, E, F, H
**Vendored** -  E

The list with this flag would show *C, D, F, H* as missing.  A is missing, but only referenced by C, which also isn't vendored, so C shows instead.  B is missing, but only referenced by D, so isn't shown.  C shows because it's directly referenced.  D is only referenced by E, but E is vendored, so D shows.  F is referenced by the unvendored H, but it's also directly referenced by the project, so it's shown anyway.  G is only referenced by H, but H is vendored, so G shows.

C, D, F, and H represent the packages that must have `fetch`/`add` run on them for all dependencies to be present in the vendor tree.  Actually, F will be included by vendoring H, but missing first-order dependencies should probably always be reported.  A and B, however, don't need to be shown at all, because vendoring C and D will automatically include A and B, respectively, due to automatic dependency inclusion.

**Comment by sean-** [comment]
Thank you for considering our case @kardianos !
