### ISSUE TITLE
govendor fails to fetch necessary file ("complex" build comment)

### ISSUE THREAD

**Issue by mlitvin** [kardianos/govendor#289]
My vendor.json file include `"ignore": "test appengine"`,
I'm trying to get a file that contain:
```
// +build appengine !linux,!freebsd,!darwin,!dragonfly,!netbsd,!openbsd
```

(taken from ([kingpin](https://github.com/alecthomas/kingpin/blob/master/guesswidth.go))

This file should be compiled on windows, but it seems that govendor ignore it because of the appengine tag.

Perhaps there should be a positive list of tags (or even list of positive tag combinations)

**Comment by kardianos** [comment]
Ah, yes, it would be good for govendor to correctly evaluate the build tags.
I'd love  a PR to correct this.
I'm not sure when I'll have time to fix this.

**Comment by johanbrandhorst** [comment]
@kardianos any pointers on where to look? I'd like to see this fixed so I might try and submit a patch.

**Comment by johanbrandhorst** [comment]
Is this the right place?
https://github.com/kardianos/govendor/blob/b680b289efed61efc520aca3ff5a66f7340f85ff/context/resolve.go#L217

**Comment by kardianos** [comment]
I'm working on a change right now. Maybe you can test on a branch once done.

**Comment by johanbrandhorst** [comment]
Ah, excellent, yes, I can test the fix on my usecase.

**Comment by kardianos** [comment]
@johanbrandhorst Could you please inspect the branch i just pushed `kardianos-tags` and verify it appears to be working?

**Comment by johanbrandhorst** [comment]
I was able to test this and unfortunately it doesn't seem to have fixed the issues. I've got the following ignore set:

```"ignore": "test appengine solaris",```

When I do a `govendor fetch github.com/lib/pq` it still excludes the `user_posix.go`, presumably because of the solaris tag, but it also now excludes a file with the tag `!windows` (ssl_permissions.go) and another file with the tag `!go1.7` (ssl_renegotiation.go) (my environment is linux amd64 with go 1.8). It also appears to have added some files that were previous excluded, `go18_test.go` and `bench_test.go`, with tags `go1.8` and `go1.1` respectively. Very confusing.

The easiest way to reproduce this I think is to start out with a clean vendor folder, fetch `github.com/lib/pq`, add `test appengine solaris` to the ignore and then fetch again.

**Comment by kardianos** [comment]
Thanks, I'll take a look at it. I appreciate your time.

If you are willing, are you able to replicate this issue by using the govendor/context/tags_test.go test?
If you are willing and able, post the file diff inline to this issue.

**Comment by johanbrandhorst** [comment]
Thanks @kardianos I'll take a look once I've finished work today (BST).

**Comment by johanbrandhorst** [comment]
This is what I tried:

```go
{
	ignoreList: "appengine test solaris",
	file:       []string{"user_posix.go"},
	buildTags:  "darwin dragonfly freebsd linux nacl netbsd openbsd solaris rumprun",
	ignored:    false,
},
```

But I was unable to reproduce the error using just the test. I can still confirm that it is ignoring the file when fetching though:
```
johan@johan-x1 ~/gows/src/myrepo/myproject $ git diff
johan@johan-x1 ~/gows/src/myrepo/myproject $ govendor fetch github.com/lib/pq
johan@johan-x1 ~/gows/src/myrepo/myproject $ git status -s
 M vendor/github.com/lib/pq/README.md
 M vendor/github.com/lib/pq/conn.go
 M vendor/github.com/lib/pq/conn_go18.go
 M vendor/github.com/lib/pq/ssl.go
 D vendor/github.com/lib/pq/ssl_permissions.go
 D vendor/github.com/lib/pq/ssl_renegotiation.go
 M vendor/github.com/lib/pq/ssl_windows.go
 D vendor/github.com/lib/pq/user_posix.go
 M vendor/vendor.json
?? vendor/github.com/lib/pq/bench_test.go
?? vendor/github.com/lib/pq/go18_test.go
```

So that's a bit curious I suppose? Sorry I can't be of more help here, it is fairly simple to reproduce using `github.com/lib/pq`, by switching the solaris tag on and off. Let me know if there's anything else I can do.

**Comment by kardianos** [comment]
That will be great. Thanks for the work on this.
