### ISSUE TITLE
feature: add a restore command

### ISSUE THREAD

**Issue by jacobsa** [kardianos/govendor#35]
It would be nice if govendor had a "restore" feature, similar to `godep restore`, that set up all of the vendored packages in `$GOPATH/src` according to their revisions listed in `vendor.json`.

This would allow you to "de-vendor" your project if you wanted to for some reason. Here are a couple of reasons I've wanted to do so:

*   In order to easily make commits in one of the libraries I depend on, based on its interactions with another library I depend on at a particular revision.

*   In order to be able to switch between vendoring tools easily: `godep restore`, followed by `rm -rf vendor Godeps`, followed by `govendor init && govendor add +e`. Having this "data portability" may increase the confidence of users to try out govendor in the first place.

**Comment by kardianos** [comment]
I'm not against adding it. I used to have an issue to track a possible restore command. I wasn't sure how the restore command should behave. 

Because I will be adding filters by tags, not all files will be copied over. Thus we don't want to touch the destination for the restore command (we can't remove all in dest before copying over vendor package). However if files were added or renamed that may break where you are restoring to. If the revision of the package is found should it revert the package to that revision before restoring? After thinking about it for a time I decided my use case/workflow was too nebulous.

As far as switching vendoring tools, I'm less convinced of that. The main point of having the vendor folder in the first place is to be mostly tool antagonistic. That may be an ideal that may not be fully realized but I don't want to optimize for that case if at all possible.

Again, I'm not against, but I want to think and document the use case and semantics of a restore command very carefully.

**Comment by jacobsa** [comment]
That's actually quite a bit more complicated that I was thinking—I don't want to cary over local modifications, just `git clone <URL>` and then `git checkout <rev>`. Maybe "restore" is the wrong word.

I hear you about having `vendor.json` in order to be tool agnostic, but unfortunately nobody but you seems to support it today. :-/

**Comment by kardianos** [comment]
Would this command be "remove" + "checkout into GOPATH" or would it be just "checkout into GOPATH"?

If just "checkout into GOPATH", it could be added as a switch in the fetch/update command in #30 . You could target the current project, or the first GOPATH env.

"govendor get -gopath +v" maybe?

**Comment by jacobsa** [comment]
Clone into `$GOPATH` and check out revision would be fine with me. You're right that this largely overlaps with #30 (although is slightly different in scope because I want a working git checkout, not just a reduced set of files copied).

**Comment by kardianos** [comment]
I'm solving this by adding the `add -uncommitted` sub-command. It isn't a full solution, but it allows you to make changes in one repo, then try them in others by adding the uncommitted changes. I'm going to argue that thinking in terms of "restore" is broken, you need to already have something committed at a revision if you want to put it in the vendor folder.
