### ISSUE TITLE
Fails on 32-bit systems

### ISSUE THREAD

**Issue by yurivict** [kardianos/govendor#386]
Getting this on FreeBSD 10 i386 with version 1.0.9:
```
vendor/github.com/Bowery/prompt/ioctl_unix.go:50:6: constant 2150396948 overflows int
vendor/github.com/Bowery/prompt/ioctl_unix.go:52:7: constant 2150396950 overflows int
```

**Comment by kaedys** [comment]
That's not an issue with govendor, that's an issue with the `prompt` library referenced.  Also, looking at the code in question, I'm honestly not even sure why that's failing, since the variables being assigned are explicitly being typed as `int64's`.  You would likely need to file a bug on that library's repository.

**Comment by NHOrus** [comment]
Fixed in https://github.com/Bowery/prompt/commit/eb8f7a6a197ce971ed0e9d4a739c628381d5f124

**Comment by yurivict** [comment]
Why did you copy dependencies instead of referencing them through modules?
Now this patch is in the prompt repository https://github.com/Bowery/prompt/commit/eb8f7a6a197ce971ed0e9d4a739c628381d5f124 but you don't have it.

**Comment by kaedys** [comment]
...what?  You vendored prompt before that patch was pushed, and haven't updated your vendored version since.  That's the entire _point_ of vendoring, to pin yourself to a particular version or revision of the dependency.  Simply update your vendored version using `govendor fetch github.com/Bowery/prompt`.  Problem solved.

**Comment by yurivict** [comment]
I didn't vendor anything, you did.
Your current version contains the outdated dependency.

**Comment by yurivict** [comment]
It's a bad idea to copy the code, it's better to at least use git modues.

----

You should make a release with updated dependencies.

**Comment by kaedys** [comment]
Ahhh, govendor vendors Bowery/prompt (ftr, I'm not the Govendor author).  @kardianos looks like we need a vendor update in govendor itself.

That said, git modules have a _lot_ of problems, and are _not_ the idiomatic solution to vendoring in Go.  Checking in source code can be argued either direction, but Kardianos went with checking it in for this repo, obviously, so it just needs an update.

**Comment by yurivict** [comment]
> That said, git modules have a lot of problems

Ok, if you don't like them, just make a release with the current dependencies, please.

**Comment by kardianos** [comment]
I'll update deps soon.

**Comment by kardianos** [comment]
Updated.

**Comment by yurivict** [comment]
Thanks! Why don't you cut a new release?
