### ISSUE TITLE
How do I build a project with govendor'd dependencies from a tarball?

### ISSUE THREAD

**Issue by lvh** [kardianos/govendor#42]
I'm trying to build `rackspace/rack` from a tarball for homebrew. `go get` works  (i.e. eventually `go build` does a thing once it's done), once `$GOPATH` is set, but that just downloads all of the dependencies from scratch. How do I convince go build to use the `internal/` package?

**Comment by kardianos** [comment]
@lvh While I don't know what is in your tarball, I am able to inspect github.com/rackspace/rack .
In rack they have copied all the needed dependencies locally. So all you need to do is just "go build" or "go install". You could even skip homebrew and just run "go get -u github.com/rackspace/rack" and it would get all the source you need to build it because all the source is in the repo.

It will use the internal directory automatically because it is using import path rewriting.

**Comment by lvh** [comment]
I've figured out the problem; not all of the dependencies were rewritten to be vendored, which is why it broke -- so it was an entirely upstream problem. You weren't able to reproduce the issue because they fixed it between the time we looked at it :) Thanks!
