### ISSUE TITLE
should revisionTime be UTC?

### ISSUE THREAD

**Issue by dpiddy** [kardianos/govendor#97]
It worries me to see a non-zero timezone offset. :)

**Comment by kardianos** [comment]
Could you expound on the worries? This wasn't an explicit design decision either way, so I'm open to hearing arguments.

For a local team, it might make more sense to record the local time plus offset. But really, the revisionTime is mainly for the maintenance programmer 10 to 20 years from now, so I'm not too worried about time of day regardless.

**Comment by dpiddy** [comment]
I gather it comes from `git show` for git but wondering if there's a case where depending on local config two runs of `govendor update` could produce different `revisionTime` values for the same UTC time.

If you are not concerned about it, feel free to close. I just generally don't like to see timestamps stored anywhere not in UTC. It's easy enough to convert to local time for display.

**Comment by kardianos** [comment]
I could buy that argument. I do want the vendor file to not change over time. Let me think about this. It will be easy to change. We parse the time first so all we have to do is call .UTC() before format.

**Comment by kaedys** [comment]
I'd like to +1 the usage of UTC.  It generally makes the vendor file easier to read, especially since the timestamps themselves seem to be using other than local time.  For example, I am in CDT (UTC -05 atm).  However, my vendor file, after a fresh Sync, has the following timezones listed: `-08, -07, -06, -05, -04, Zulu, +01, +02, +09, +11`.  While not, strictly speaking, necessarily a problem, it _is_ nice to have them all in the same timezone.  I can certainly foresee annoyance when trying to determine if your latest revision of package A, which has package B as a vendored dependency, was released before or after the latest version X of B was available.
